[project]
authors = ["hydrogen-labs"]
entry = "main.sw"
license = "Apache-2.0"
name = "trove-manager-contract"

[dependencies]
libraries = { path = "../../libraries" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.1" }
